server:
  port: 8091

spring:
  config:
    import: configserver:http://localhost:8888
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: AUTHENTICATION-SERVICE
management:
  endpoints:
    web:
      exposure:
        include: "*"



