server:
  port: 8090

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/auth/**

        - id: carbids-lots-service
          uri: lb://CARBIDS-LOTS-SERVICE
          predicates:
            - Path=/api/lot/**

        - id: carbids-bidding-service
          uri: lb://CARBIDS-BIDDING-SERVICE
          predicates:
            - Path=/api/bid/**

        - id: carbids-comment-service
          uri: lb://CARBIDS-COMMENT-SERVICE
          predicates:
            - Path=/api/comment/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8765/eureka