server:
  port: 8090

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/auth/**

        - id: test-private-server
          uri: lb://TEST-PRIVATE-SERVER
          predicates:
            - Path=/private/**
          filters:
            - AuthenticationFilter

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka