server:
  port: 8093

spring:
  config:
    import: configserver:http://localhost:8888
  application:
    name: CARBIDS-LOTS-SERVICE
management:
  endpoints:
    web:
      exposure:
        include: "*"


