server:
  port: 8095

spring:
  application:
    name: TEST-PRIVATE-SERVER

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
